const helpTexts = {
  English: {
    "Axis Count": "Defines the number of axes for machining operations.",
    "Strategy": "Defines the cutting strategy used for profiling operations.",
    "Geometry Source": "Specifies the source geometry for toolpath generation.",
    "Curve Source": "Defines the curve used as a base for toolpath operations.",
    "Curve Target": "Specifies the target curve for toolpath projection.",
    "A Axis Rotation": "Rotates the part around the A axis.",
    "B Axis Rotation": "Rotates the part around the B axis.",
    "X Count": "Defines the number of duplicates along the X axis.",
    "X Distance (mm)": "Sets the spacing between duplicates in the X direction.",
    "Y Count": "Defines the number of duplicates along the Y axis.",
    "Y Distance (mm)": "Sets the spacing between duplicates in the Y direction.",
    "Bridge Width (mm)": "Defines the width of bridge connections between parts.",
    "Bridge Height (mm)": "Defines the height of bridges to hold cut parts in place.",
    "Use Modifiers": "Applies additional processing modifications to bridges.",
    "Start Depth (mm)": "Initial depth of the operation.",
    "Max Depth (mm)": "Maximum depth of the cut.",
    "First Down": "Enables an initial down movement before cutting.",
    "Cutter Type": "Specifies the type of cutter used for the operation.",
    "Cutter Diameter (mm)": "Defines the diameter of the cutting tool.",
    "Flutes": "Number of flutes on the cutter.",
    "Tool Number": "Identifier number for the selected tool.",
    "Description": "Additional description of the cutter.",
    "Feedrate (mm/min)": "The speed at which the tool moves through the material.",
    "Spindle Speed (RPM)": "The rotational speed of the spindle.",
    "Plunge Speed (%)": "The speed at which the tool plunges into the material.",
    "Plunge Angle (°)": "The angle at which the tool enters the material.",
    "Milling Type": "Defines the direction of the cutting motion.",
    "Cutter Spin": "Determines the rotation direction of the spindle.",
    "Protect Vertical": "Enables safety mechanisms for vertical movements.",
    "Angle Limit (°)": "Restricts the maximum allowed toolpath angle.",
    "Detail Size (mm)": "Specifies the level of detail for the toolpath.",
    "Max Resolution (MP)": "Defines the maximum resolution for generated toolpaths.",
    "Reduce Path Points": "Optimizes toolpath by reducing unnecessary points.",
    "Threshold (μm)": "Sets the threshold for path point reduction.",
    "Output Header": "Enables a custom G-code header at the start of the file.",
    "Output Trailer": "Enables a custom G-code trailer at the end of the file.",
    "Enable Dust Collector": "Activates the dust extraction system during machining.",
    "Enable Mist Cooling": "Activates mist cooling to improve tool life and surface finish."
  },
  French: {
    "Axis Count": "Définit le nombre d'axes pour les opérations d'usinage.",
    "Strategy": "Définit la stratégie de coupe utilisée pour les opérations de profilage.",
    "Geometry Source": "Spécifie la source de la géométrie pour la génération de trajectoires d'outil.",
    "Curve Source": "Définit la courbe utilisée comme base pour les opérations de trajectoire d'outil.",
    "Curve Target": "Spécifie la courbe cible pour la projection de la trajectoire d'outil.",
    "A Axis Rotation": "Fait tourner la pièce autour de l'axe A.",
    "B Axis Rotation": "Fait tourner la pièce autour de l'axe B.",
    "X Count": "Définit le nombre de duplicatas le long de l'axe X.",
    "X Distance (mm)": "Définit l'espacement entre les duplicatas dans la direction X.",
    "Y Count": "Définit le nombre de duplicatas le long de l'axe Y.",
    "Y Distance (mm)": "Définit l'espacement entre les duplicatas dans la direction Y.",
    "Bridge Width (mm)": "Définit la largeur des connexions de pont entre les pièces.",
    "Bridge Height (mm)": "Définit la hauteur des ponts pour maintenir les pièces coupées en place.",
    "Use Modifiers": "Applique des modifications de traitement supplémentaires aux ponts.",
    "Start Depth (mm)": "Profondeur initiale de l'opération.",
    "Max Depth (mm)": "Profondeur maximale de la coupe.",
    "First Down": "Active un mouvement initial vers le bas avant la coupe.",
    "Cutter Type": "Spécifie le type de fraise utilisé pour l'opération.",
    "Cutter Diameter (mm)": "Définit le diamètre de l'outil de coupe.",
    "Flutes": "Nombre de cannelures sur la fraise.",
    "Tool Number": "Numéro d'identification de l'outil sélectionné.",
    "Description": "Description supplémentaire de la fraise.",
    "Feedrate (mm/min)": "La vitesse à laquelle l'outil se déplace à travers le matériau.",
    "Spindle Speed (RPM)": "La vitesse de rotation de la broche.",
    "Plunge Speed (%)": "La vitesse à laquelle l'outil plonge dans le matériau.",
    "Plunge Angle (°)": "L'angle auquel l'outil entre dans le matériau.",
    "Milling Type": "Définit la direction du mouvement de coupe.",
    "Cutter Spin": "Détermine la direction de rotation de la broche.",
    "Protect Vertical": "Active les mécanismes de sécurité pour les mouvements verticaux.",
    "Angle Limit (°)": "Limite l'angle maximal autorisé de la trajectoire de l'outil.",
    "Detail Size (mm)": "Spécifie le niveau de détail pour la trajectoire de l'outil.",
    "Max Resolution (MP)": "Définit la résolution maximale pour les trajectoires d'outil générées.",
    "Reduce Path Points": "Optimise la trajectoire de l'outil en réduisant les points inutiles.",
    "Threshold (μm)": "Définit le seuil pour la réduction des points de trajectoire.",
    "Output Header": "Active un en-tête G-code personnalisé au début du fichier.",
    "Output Trailer": "Active une bande-annonce G-code personnalisée à la fin du fichier.",
    "Enable Dust Collector": "Active le système d'extraction de poussière pendant l'usinage.",
    "Enable Mist Cooling": "Active le refroidissement par brouillard pour améliorer la durée de vie de l'outil et la finition de surface."
  }
};

export default helpTexts;
